/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_BIRD_ONESHOT_VADPCM_H
#define AMBIENCE_BIRD_ONESHOT_VADPCM_H

#define AMBIENCE_BIRD_ONESHOT_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_BIRD_ONESHOT_VADPCM_SAMPLE_COUNT 155040
#define AMBIENCE_BIRD_ONESHOT_VADPCM_DATA_BYTES 87210
#define AMBIENCE_BIRD_ONESHOT_VADPCM_BOOK_ORDER 2
#define AMBIENCE_BIRD_ONESHOT_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_BIRD_ONESHOT_VADPCM_BOOK_VALUES { \
   -1935,   1153,   1141,  -1769,    -24,   1685,   -982,  -1007, \
   -1220,  -1208,   1873,     25,  -1784,   1040,   1066,  -1617, \
   -1614,   -928,    738,   1156,     83,   -863,   -562,    357, \
    1178,   -937,  -1467,   -105,   1095,    713,   -453,   -823, \
   -1761,   1649,    -31,  -1389,   1327,    -49,  -1095,   1067, \
   -1918,     36,   1615,  -1543,     57,   1274,  -1242,     68, \
   -1901,    329,   1707,   -602,  -1480,    815,   1233,   -970, \
    -355,  -1839,    648,   1595,   -878,  -1328,   1045,   1051, \
}
#define AMBIENCE_BIRD_ONESHOT_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_BIRD_ONESHOT_VADPCM_H */
