/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_BIRD_VADPCM_H
#define AMBIENCE_BIRD_VADPCM_H

#define AMBIENCE_BIRD_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_BIRD_VADPCM_SAMPLE_COUNT 155040
#define AMBIENCE_BIRD_VADPCM_DATA_BYTES 87210
#define AMBIENCE_BIRD_VADPCM_BOOK_ORDER 2
#define AMBIENCE_BIRD_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_BIRD_VADPCM_BOOK_VALUES { \
   -1934,   1151,   1142,  -1766,    -28,   1684,   -976,  -1010, \
   -1218,  -1209,   1870,     29,  -1783,   1033,   1069,  -1612, \
   -1614,   -929,    738,   1156,     83,   -863,   -562,    357, \
    1178,   -936,  -1467,   -106,   1095,    714,   -453,   -823, \
   -1761,   1649,    -31,  -1389,   1327,    -49,  -1095,   1067, \
   -1918,     36,   1615,  -1543,     57,   1274,  -1242,     68, \
   -1902,    326,   1711,   -597,  -1487,    809,   1242,   -965, \
    -351,  -1842,    642,   1601,   -871,  -1338,   1039,   1064, \
}
#define AMBIENCE_BIRD_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_BIRD_VADPCM_H */
