/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_FOREST_LOOP_VADPCM_H
#define AMBIENCE_FOREST_LOOP_VADPCM_H

#define AMBIENCE_FOREST_LOOP_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_FOREST_LOOP_VADPCM_SAMPLE_COUNT 140640
#define AMBIENCE_FOREST_LOOP_VADPCM_DATA_BYTES 79110
#define AMBIENCE_FOREST_LOOP_VADPCM_BOOK_ORDER 2
#define AMBIENCE_FOREST_LOOP_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_FOREST_LOOP_VADPCM_BOOK_VALUES { \
   -1889,   1805,     18,  -1682,   1590,     32,  -1497,   1401, \
   -1957,    -20,   1823,  -1724,    -35,   1623,  -1519,    -46, \
   -1868,   -232,   1674,    419,  -1475,   -565,   1275,    673, \
     254,  -1836,   -459,   1617,    620,  -1398,   -739,   1183, \
   -1725,   2462,  -2061,    868,    497,  -1440,   1637,  -1123, \
   -2923,   2447,  -1030,   -590,   1710,  -1943,   1334,   -267, \
   -1950,    832,   1502,  -1434,   -818,   1715,     47,  -1653, \
    -874,  -1577,   1506,    859,  -1801,    -50,   1736,   -694, \
}
#define AMBIENCE_FOREST_LOOP_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_FOREST_LOOP_VADPCM_H */
