/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_INSECTS_LOOP_VADPCM_H
#define AMBIENCE_INSECTS_LOOP_VADPCM_H

#define AMBIENCE_INSECTS_LOOP_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_INSECTS_LOOP_VADPCM_SAMPLE_COUNT 129600
#define AMBIENCE_INSECTS_LOOP_VADPCM_DATA_BYTES 72900
#define AMBIENCE_INSECTS_LOOP_VADPCM_BOOK_ORDER 2
#define AMBIENCE_INSECTS_LOOP_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_INSECTS_LOOP_VADPCM_BOOK_VALUES { \
     250,    202,    194,    182,    171,    161,    151,    142, \
    1658,   1592,   1491,   1401,   1316,   1237,   1162,   1091, \
    1521,    309,   1193,    471,    981,    549,    840,    578, \
     415,   1606,    634,   1321,    739,   1131,    779,    998, \
   -1491,  -2484,  -3054,  -3280,  -3242,  -3014,  -2661,  -2240, \
    3412,   4195,   4505,   4453,   4139,   3655,   3077,   2466, \
    1674,    -32,   1369,    -53,   1121,    -65,    917,    -71, \
     -39,   1675,    -64,   1371,    -79,   1122,    -86,    919, \
}
#define AMBIENCE_INSECTS_LOOP_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_INSECTS_LOOP_VADPCM_H */
