/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_INSECTS_VADPCM_H
#define AMBIENCE_INSECTS_VADPCM_H

#define AMBIENCE_INSECTS_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_INSECTS_VADPCM_SAMPLE_COUNT 129600
#define AMBIENCE_INSECTS_VADPCM_DATA_BYTES 72900
#define AMBIENCE_INSECTS_VADPCM_BOOK_ORDER 2
#define AMBIENCE_INSECTS_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_INSECTS_VADPCM_BOOK_VALUES { \
     249,    202,    194,    181,    170,    160,    150,    141, \
    1658,   1592,   1491,   1401,   1316,   1236,   1161,   1090, \
    1521,    308,   1193,    471,    982,    549,    840,    578, \
     415,   1606,    634,   1321,    739,   1131,    778,    998, \
   -1492,  -2486,  -3057,  -3283,  -3245,  -3017,  -2665,  -2243, \
    3413,   4197,   4508,   4456,   4143,   3659,   3080,   2468, \
    1674,    -32,   1369,    -53,   1120,    -65,    917,    -71, \
     -40,   1675,    -65,   1371,    -79,   1122,    -87,    919, \
}
#define AMBIENCE_INSECTS_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_INSECTS_VADPCM_H */
