/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_LAVA_VADPCM_H
#define AMBIENCE_LAVA_VADPCM_H

#define AMBIENCE_LAVA_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_LAVA_VADPCM_SAMPLE_COUNT 135840
#define AMBIENCE_LAVA_VADPCM_DATA_BYTES 76410
#define AMBIENCE_LAVA_VADPCM_BOOK_ORDER 2
#define AMBIENCE_LAVA_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_LAVA_VADPCM_BOOK_VALUES { \
   -2042,  -4062,  -6045,  -7974,  -9836, -11615, -13299, -14874, \
    4074,   6062,   7997,   9865,  11649,  13338,  14918,  16376, \
   -2039,  -3883,  -5366,  -6354,  -6760,  -6549,  -5744,  -4420, \
    3901,   5390,   6383,   6790,   6579,   5770,   4440,   2712, \
   -2045,  -4033,  -5914,  -7639,  -9164, -10450, -11463, -12178, \
    4040,   5924,   7652,   9179,  10467,  11482,  12198,  12598, \
   -1908,  -3593,  -4988,  -6046,  -6738,  -7055,  -7008,  -6624, \
    3857,   5354,   6490,   7232,   7573,   7522,   7110,   6380, \
}
#define AMBIENCE_LAVA_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_LAVA_VADPCM_H */
