/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_LAVA_LOOP_VADPCM_H
#define AMBIENCE_LAVA_LOOP_VADPCM_H

#define AMBIENCE_LAVA_LOOP_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_LAVA_LOOP_VADPCM_SAMPLE_COUNT 135840
#define AMBIENCE_LAVA_LOOP_VADPCM_DATA_BYTES 76410
#define AMBIENCE_LAVA_LOOP_VADPCM_BOOK_ORDER 2
#define AMBIENCE_LAVA_LOOP_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_LAVA_LOOP_VADPCM_BOOK_VALUES { \
   -2048,  -4082,  -6089,  -8053,  -9962, -11802, -13562, -15228, \
    4082,   6088,   8052,   9961,  11802,  13561,  15226,  16787, \
   -2028,  -3854,  -5317,  -6288,  -6685,  -6478,  -5692,  -4403, \
    3892,   5369,   6350,   6751,   6542,   5748,   4446,   2758, \
   -2026,  -3947,  -5685,  -7172,  -8348,  -9171,  -9608,  -9648, \
    3990,   5747,   7250,   8440,   9271,   9714,   9754,   9394, \
   -2023,  -3984,  -5847,  -7578,  -9146, -10524, -11688, -12619, \
    4033,   5919,   7670,   9258,  10652,  11830,  12773,  13464, \
}
#define AMBIENCE_LAVA_LOOP_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_LAVA_LOOP_VADPCM_H */
