/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_RAIN_LOOP_VADPCM_H
#define AMBIENCE_RAIN_LOOP_VADPCM_H

#define AMBIENCE_RAIN_LOOP_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_RAIN_LOOP_VADPCM_SAMPLE_COUNT 120000
#define AMBIENCE_RAIN_LOOP_VADPCM_DATA_BYTES 67500
#define AMBIENCE_RAIN_LOOP_VADPCM_BOOK_ORDER 2
#define AMBIENCE_RAIN_LOOP_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_RAIN_LOOP_VADPCM_BOOK_VALUES { \
    -605,   -353,    -27,     88,     60,      9,    -13,    -10, \
    1194,     92,   -299,   -202,    -29,     42,     33,      7, \
    -327,   -369,   -364,   -351,   -338,   -326,   -313,   -302, \
    2310,   2280,   2203,   2121,   2042,   1965,   1891,   1819, \
    -215,    -29,     19,      6,     -1,     -1,      0,      0, \
     279,   -177,    -54,     11,      7,      0,     -1,      0, \
    -968,   -269,    382,    233,   -116,   -142,     15,     72, \
     569,   -809,   -494,    245,    302,    -32,   -151,    -27, \
}
#define AMBIENCE_RAIN_LOOP_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_RAIN_LOOP_VADPCM_H */
