/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_RAIN_VADPCM_H
#define AMBIENCE_RAIN_VADPCM_H

#define AMBIENCE_RAIN_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_RAIN_VADPCM_SAMPLE_COUNT 120000
#define AMBIENCE_RAIN_VADPCM_DATA_BYTES 67500
#define AMBIENCE_RAIN_VADPCM_BOOK_ORDER 2
#define AMBIENCE_RAIN_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_RAIN_VADPCM_BOOK_VALUES { \
    -606,   -354,    -27,     89,     60,      9,    -13,    -10, \
    1195,     91,   -301,   -202,    -29,     43,     34,      7, \
    -327,   -369,   -364,   -351,   -338,   -326,   -313,   -302, \
    2310,   2279,   2203,   2121,   2042,   1965,   1891,   1819, \
    -212,    -29,     18,      5,     -1,     -1,      0,      0, \
     281,   -174,    -53,     11,      7,      0,     -1,      0, \
    -967,   -267,    382,    232,   -116,   -142,     16,     71, \
     566,   -810,   -491,    247,    300,    -33,   -151,    -26, \
}
#define AMBIENCE_RAIN_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_RAIN_VADPCM_H */
