/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_UNDERWATER_LOOP_VADPCM_H
#define AMBIENCE_UNDERWATER_LOOP_VADPCM_H

#define AMBIENCE_UNDERWATER_LOOP_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_UNDERWATER_LOOP_VADPCM_SAMPLE_COUNT 92640
#define AMBIENCE_UNDERWATER_LOOP_VADPCM_DATA_BYTES 52110
#define AMBIENCE_UNDERWATER_LOOP_VADPCM_BOOK_ORDER 2
#define AMBIENCE_UNDERWATER_LOOP_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_UNDERWATER_LOOP_VADPCM_BOOK_VALUES { \
   -2061,  -3805,  -4951,  -5311,  -4822,  -3558,  -1716,    414, \
    3781,   4919,   5277,   4792,   3535,   1705,   -411,  -2474, \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
   -2044,  -4041,  -5949,  -7727,  -9338, -10747, -11926, -12850, \
    4049,   5960,   7741,   9355,  10767,  11948,  12873,  13524, \
   -1995,  -3839,  -5440,  -6724,  -7635,  -8135,  -8211,  -7868, \
    3940,   5583,   6901,   7836,   8350,   8427,   8075,   7323, \
}
#define AMBIENCE_UNDERWATER_LOOP_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_UNDERWATER_LOOP_VADPCM_H */
