/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_UNDERWATER_VADPCM_H
#define AMBIENCE_UNDERWATER_VADPCM_H

#define AMBIENCE_UNDERWATER_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_UNDERWATER_VADPCM_SAMPLE_COUNT 92640
#define AMBIENCE_UNDERWATER_VADPCM_DATA_BYTES 52110
#define AMBIENCE_UNDERWATER_VADPCM_BOOK_ORDER 2
#define AMBIENCE_UNDERWATER_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_UNDERWATER_VADPCM_BOOK_VALUES { \
   -2061,  -3805,  -4951,  -5311,  -4822,  -3558,  -1715,    414, \
    3781,   4919,   5277,   4791,   3535,   1704,   -412,  -2475, \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
   -2044,  -4041,  -5949,  -7727,  -9338, -10747, -11927, -12851, \
    4049,   5960,   7741,   9355,  10767,  11949,  12875,  13526, \
   -1997,  -3842,  -5446,  -6734,  -7649,  -8154,  -8233,  -7893, \
    3941,   5586,   6908,   7846,   8364,   8445,   8096,   7347, \
}
#define AMBIENCE_UNDERWATER_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_UNDERWATER_VADPCM_H */
