/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_WIND_VADPCM_H
#define AMBIENCE_WIND_VADPCM_H

#define AMBIENCE_WIND_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_WIND_VADPCM_SAMPLE_COUNT 113760
#define AMBIENCE_WIND_VADPCM_DATA_BYTES 63990
#define AMBIENCE_WIND_VADPCM_BOOK_ORDER 2
#define AMBIENCE_WIND_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_WIND_VADPCM_BOOK_VALUES { \
    -379,   -451,   -466,   -471,   -473,   -476,   -478,   -480, \
    2435,   2516,   2541,   2556,   2568,   2581,   2593,   2605, \
     218,    182,    175,    165,    156,    148,    140,    132, \
    1707,   1641,   1549,   1466,   1387,   1312,   1241,   1174, \
   -1259,  -2002,  -2411,  -2604,  -2660,  -2631,  -2549,  -2438, \
    3257,   3922,   4237,   4328,   4281,   4148,   3967,   3761, \
    -535,   -630,   -603,   -546,   -486,   -430,   -380,   -335, \
    2413,   2309,   2090,   1860,   1645,   1453,   1282,   1132, \
}
#define AMBIENCE_WIND_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_WIND_VADPCM_H */
