/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef AMBIENCE_WIND_LOOP_VADPCM_H
#define AMBIENCE_WIND_LOOP_VADPCM_H

#define AMBIENCE_WIND_LOOP_VADPCM_SAMPLE_RATE 12000
#define AMBIENCE_WIND_LOOP_VADPCM_SAMPLE_COUNT 113760
#define AMBIENCE_WIND_LOOP_VADPCM_DATA_BYTES 63990
#define AMBIENCE_WIND_LOOP_VADPCM_BOOK_ORDER 2
#define AMBIENCE_WIND_LOOP_VADPCM_BOOK_PREDICTORS 4
#define AMBIENCE_WIND_LOOP_VADPCM_BOOK_VALUES { \
    -380,   -451,   -467,   -471,   -474,   -476,   -479,   -481, \
    2436,   2517,   2542,   2557,   2569,   2582,   2594,   2607, \
     218,    181,    174,    165,    156,    148,    140,    132, \
    1708,   1642,   1551,   1468,   1389,   1314,   1243,   1176, \
   -1259,  -2002,  -2410,  -2604,  -2660,  -2630,  -2549,  -2438, \
    3257,   3922,   4237,   4328,   4280,   4148,   3967,   3761, \
    -535,   -631,   -603,   -546,   -486,   -430,   -380,   -335, \
    2414,   2309,   2090,   1860,   1646,   1453,   1282,   1131, \
}
#define AMBIENCE_WIND_LOOP_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* AMBIENCE_WIND_LOOP_VADPCM_H */
