/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef MUSIC_GAME_VADPCM_H
#define MUSIC_GAME_VADPCM_H

#define MUSIC_GAME_VADPCM_SAMPLE_RATE 22050
#define MUSIC_GAME_VADPCM_SAMPLE_COUNT 2376992
#define MUSIC_GAME_VADPCM_DATA_BYTES 1337058
#define MUSIC_GAME_VADPCM_BOOK_ORDER 2
#define MUSIC_GAME_VADPCM_BOOK_PREDICTORS 4
#define MUSIC_GAME_VADPCM_BOOK_VALUES { \
   -1983,  -3888,  -5706,  -7427,  -9042, -10543, -11924, -13180, \
    4017,   5895,   7672,   9340,  10891,  12318,  13615,  14776, \
     -89,    -93,    -92,    -91,    -90,    -90,    -89,    -88, \
    2121,   2106,   2088,   2071,   2053,   2035,   2018,   2000, \
   -1099,  -1596,  -1731,  -1659,  -1483,  -1265,  -1043,   -837, \
    2976,   3227,   3093,   2764,   2358,   1944,   1560,   1225, \
   -1986,  -3820,  -5422,  -6727,  -7683,  -8257,  -8434,  -8218, \
    3940,   5593,   6938,   7924,   8516,   8698,   8476,   7870, \
}
#define MUSIC_GAME_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* MUSIC_GAME_VADPCM_H */
