/* Generated by tools/audio_codegen.py; do not edit. */
#ifndef MUSIC_TITLE_VADPCM_H
#define MUSIC_TITLE_VADPCM_H

#define MUSIC_TITLE_VADPCM_SAMPLE_RATE 22050
#define MUSIC_TITLE_VADPCM_SAMPLE_COUNT 2302912
#define MUSIC_TITLE_VADPCM_DATA_BYTES 1295388
#define MUSIC_TITLE_VADPCM_BOOK_ORDER 2
#define MUSIC_TITLE_VADPCM_BOOK_PREDICTORS 4
#define MUSIC_TITLE_VADPCM_BOOK_VALUES { \
   -1863,  -3549,  -5062,  -6412,  -7604,  -8647,  -9548, -10314, \
    3900,   5564,   7047,   8357,   9503,  10493,  11336,  12040, \
    -468,   -557,   -556,   -535,   -509,   -484,   -460,   -437, \
    2438,   2434,   2340,   2230,   2120,   2014,   1913,   1817, \
    -726,   -777,   -574,   -339,   -159,    -50,      3,     21, \
    2192,   1619,    956,    449,    141,     -8,    -59,    -60, \
     720,    467,    556,    525,    536,    532,    534,    533, \
    1328,   1582,   1493,   1524,   1514,   1518,   1517,   1517, \
}
#define MUSIC_TITLE_VADPCM_LOOP_STATE { \
       0,      0,      0,      0,      0,      0,      0,      0, \
       0,      0,      0,      0,      0,      0,      0,      0, \
}

#endif /* MUSIC_TITLE_VADPCM_H */
