#!/usr/bin/env python3
"""Extract N64 VADPCM payload/codebook data into ROM and C build assets."""

import argparse
import struct
from pathlib import Path


def parse_vadpcm_aifc(path: Path) -> tuple[int, int, int, list[int], bytes]:
    data = path.read_bytes()
    if len(data) < 12 or data[:4] != b"FORM" or data[8:12] != b"AIFC":
        raise ValueError("expected a VADPCM AIFF-C file")
    form_end = struct.unpack_from(">I", data, 4)[0] + 8
    if form_end > len(data):
        raise ValueError("truncated FORM chunk")

    sample_rate = sample_count = None
    encoded_data = None
    codebook = None
    offset = 12
    while offset + 8 <= form_end:
        chunk_id = data[offset : offset + 4]
        size = struct.unpack_from(">I", data, offset + 4)[0]
        start, end = offset + 8, offset + 8 + size
        if end > form_end:
            raise ValueError("truncated AIFF-C chunk")
        chunk = data[start:end]
        if chunk_id == b"COMM":
            if len(chunk) < 23 or chunk[18:22] != b"VAPC":
                raise ValueError("expected a VAPC COMM chunk")
            channels, sample_count, bits = struct.unpack_from(">HIH", chunk)
            if channels != 1 or bits != 16:
                raise ValueError("VADPCM music must be mono 16-bit")
            sign_exponent, fraction = struct.unpack_from(">HQ", chunk, 8)
            exponent = (sign_exponent & 0x7FFF) - 16383
            sample_rate = round(fraction * (2.0 ** (exponent - 63)))
        elif chunk_id == b"SSND":
            if len(chunk) < 8:
                raise ValueError("short SSND chunk")
            data_offset = struct.unpack_from(">I", chunk)[0]
            start_of_audio = 8 + data_offset
            if start_of_audio > len(chunk):
                raise ValueError("invalid SSND offset")
            encoded_data = chunk[start_of_audio:]
        elif chunk_id == b"APPL" and len(chunk) >= 22 and chunk[:4] == b"stoc":
            name_length = chunk[4]
            name_end = 5 + name_length
            if name_length == 11 and chunk[5:name_end] == b"VADPCMCODES":
                codebook_offset = 4 + ((name_length + 2) & ~1)
                version, order, predictors = struct.unpack_from(">HHH", chunk, codebook_offset)
                if version != 1:
                    raise ValueError(f"unsupported VADPCM codebook version {version}")
                value_count = order * predictors * 8
                values = list(struct.unpack_from(f">{value_count}h", chunk, codebook_offset + 6))
                codebook = order, predictors, values
        offset = end + (size & 1)

    if sample_rate is None or sample_count is None or encoded_data is None or codebook is None:
        raise ValueError("missing VADPCM audio data or codebook")
    if len(encoded_data) != (sample_count // 16) * 9:
        raise ValueError("VADPCM payload length does not match sample count")
    return sample_rate, sample_count, *codebook, encoded_data


def format_values(values: list[int]) -> str:
    rows = [values[index : index + 8] for index in range(0, len(values), 8)]
    return " \\\n".join("  " + ", ".join(f"{value:6d}" for value in row) + "," for row in rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="VADPCM AIFC input")
    parser.add_argument("binary", type=Path, help="raw VADPCM output")
    parser.add_argument("header", type=Path, help="generated C metadata header")
    parser.add_argument("symbol", help="upper-case C symbol prefix, e.g. MUSIC_TITLE")
    args = parser.parse_args()

    rate, samples, order, predictors, values, encoded = parse_vadpcm_aifc(args.input)
    guard = f"{args.symbol}_VADPCM_H"
    args.binary.parent.mkdir(parents=True, exist_ok=True)
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.binary.write_bytes(encoded)
    args.header.write_text(
        "/* Generated by tools/audio_codegen.py; do not edit. */\n"
        f"#ifndef {guard}\n#define {guard}\n\n"
        f"#define {args.symbol}_VADPCM_SAMPLE_RATE {rate}\n"
        f"#define {args.symbol}_VADPCM_SAMPLE_COUNT {samples}\n"
        f"#define {args.symbol}_VADPCM_DATA_BYTES {len(encoded)}\n"
        f"#define {args.symbol}_VADPCM_BOOK_ORDER {order}\n"
        f"#define {args.symbol}_VADPCM_BOOK_PREDICTORS {predictors}\n"
        f"#define {args.symbol}_VADPCM_BOOK_VALUES {{ \\\n{format_values(values)} \\\n}}\n\n"
        f"#endif /* {guard} */\n",
        encoding="utf-8",
    )
    print(f"{args.symbol}: {len(encoded):,} bytes, {samples / rate:.3f} s at {rate} Hz")


if __name__ == "__main__":
    main()
